version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
      - npm install --silent --no-progress
      - cd $CODEBUILD_SRC_DIR/services/lahiyam-website && npm install --silent --no-progress
      - cd $CODEBUILD_SRC_DIR/services/blog-api && npm install --silent --no-progress
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run test
      - mkdir -p target/dev
      - mkdir target/prod
      - npm run package-all

artifacts:
  files:
    - services/**/target/**/*
    - services/**/serverless.yml
    - serverless.common.yml
    - deploy.sh
    - package.json
    - services/**/package.json
