import {
  attribute,
  autoGeneratedHashKey,
  table
} from "@aws/dynamodb-data-mapper-annotations";

const stage = process.env.stage === "prod" ? "prod" : "dev";

@table(`${stage}-lahiyam-posts-table`)
export default class Post {
  @autoGeneratedHashKey()
  id: string;

  @attribute({
    defaultProvider: () => Date.now(),
    indexKeyConfigurations: {
      "userId-createdAt-index": "RANGE"
    }
  })
  createdAt?: number;

  @attribute()
  title?: string;

  @attribute({
    indexKeyConfigurations: {
      "userId-createdAt-index": "HASH"
    }
  })
  userId: string;

  @attribute()
  content?: string;

  @attribute({ type: "Collection" })
  tags?: Array<string>;
}
